const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Adidas Slim Pants",
      category: "Shirt",
      image: "/images/p6.jpg",
      price: 330,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 19,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pants",
      category: "Shirt",
      image: "/images/p5.jpg",
      price: 200,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 23,
      description: "high quality product",
    },
  ],
};
export default data;
