import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "khanoomi",
      email: "admin-1@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Akbar agha",
      email: "user@example.com",
      password: bcrypt.hashSync("12345", 8),
      isAdmin: false,
    },
    {
      name: "Ziba",
      email: "user_1@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
    {
      name: "Iman",
      email: "user_3@example.com",
      password: bcrypt.hashSync("12345678", 8),
      isAdmin: false,
    },
    {
      name: "Mehdi",
      email: "user_2@example.com",
      password: bcrypt.hashSync("123456789", 8),
      isAdmin: false,
    },
    {
      name: "Shabnam",
      email: "user_5@example.com",
      password: bcrypt.hashSync("1234567890", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slims Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidass Fit Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 30,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirts",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 40,
      brand: "Nike",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 78,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Adidas Slim Pants ",
      category: "Shirt",
      image: "/images/p6.jpg",
      price: 330,
      countInStock: 25,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 19,
      description: "high quality product",
    },
    {
      name: "Adidas Slim Pants sade",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 200,
      countInStock: 35,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 23,
      description: "high quality product",
    },
    {
      name: "Adidas Slims Pants ",
      category: "Shirt",
      image: "/images/p6.jpg",
      price: 330,
      countInStock: 25,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 19,
      description: "high quality product",
    },
  ],
};
export default data;
